
import "@/node_modules/react-modal-video/css/modal-video.css"
import "../public/assets/css/style.css"
import 'swiper/css'
// import "swiper/css/navigation"
import "swiper/css/pagination"
import 'swiper/css/free-mode';
import { dM_Sans, } from '@/lib/font'
import Script from "next/script";
import { useEffect } from "react";
import { usePathname } from "next/navigation";
export const metadata = {
    title: 'Namko Builders',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
     const pathname = usePathname();

  useEffect(() => {
    gtag.pageview(pathname);
  }, [pathname]);

    return (
        <html lang="en" className={`${dM_Sans.variable}`}>
            <body>
                {/* Google Analytics */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-T296N1N6H6`}
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-T296N1N6H6');
          `}
        </Script>
                {children}</body>
        </html>
    )
}
